[package]
name = "rox-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
console = "0.15.1"
pathdiff = "0.2.1"
glob = "0.3.0"
clap = { version = "4.0.10", features = ["derive"] }
